import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import GetProductsWrapper from "@/wrappers/GetProductsWrapper";
import Theme from "@/wrappers/GetThemeWrapper";
import { ModeToggle } from "@/components/Toggle";
import { ThemeProvider } from "@/wrappers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <GetProductsWrapper>
            <ModeToggle />
            <Navbar />
            <Theme />
            {children}
          </GetProductsWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
